# Generated by Django 2.2.24 on 2022-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_auto_20220122_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
