# Generated by Django 2.2.24 on 2022-02-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_cvs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cvs',
        ),
    ]
