# Generated by Django 2.2 on 2022-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_delete_cvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='job_image/'),
        ),
    ]
