# Generated by Django 2.2 on 2022-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20220401_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
