# Generated by Django 2.2 on 2022-04-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20220401_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
    ]
